# Part 2

# Set up 3 applications that will run on k3s.
# They will have to be accessible via the HOST header when making a request to
#	192.168.56.110
# If no HOST header is found, app3 is selected by default.
# The app2 must have three replicas

SERVER_NAME = "nguiardS"
SERVER_IP = "192.168.56.110"

Vagrant.configure("2") do |config|
	config.vm.box = "debian/bookworm64"

  config.vm.provider "virtualbox" do |v|
      v.memory = 1024
      v.cpus = 1
  end

	# Server
	config.vm.define SERVER_NAME do |server|
		server.vm.hostname = SERVER_NAME
    server.vm.network "forwarded_port", guest: 80, host: 8080
		server.vm.network "private_network", ip: SERVER_IP

    server.vm.provision "shell", path: "scripts/Server.sh"
    server.vm.provision "shell",
      inline: "sudo kubectl apply -f /vagrant/config.yaml",
      name: "apply-config"
  end
end
