# Part 2

# Set up 3 applications that will run on k3s.
# They will have to be accessible via the HOST header when making a request to
#	192.168.56.110
# If no HOST header is found, app3 is selected by default.
# The app2 must have three replicas

SERVER_NAME = "nguiardS"
SERVER_IP = "192.168.56.110"
APP1_NAME = "app-one"
APP1_IP = "192.168.56.111"
APP2_NAME = "app-two"
APP2_IP = "192.168.56.112"
APP3_NAME = "app-three"
APP3_IP = "192.168.56.113"

Vagrant.configure("2") do |config|
	config.vm.box = "debian/bookworm64"

  # common for all vagrant boxes
  config.vm.provider "virtualbox" do |v|
      v.memory = 1024
      v.cpus = 1
  end

	# Server
	config.vm.define SERVER_NAME do |server|
		server.vm.hostname = SERVER_NAME
		server.vm.network "private_network", ip: SERVER_IP

    server.vm.provision "shell",
      path: "scripts/Server.sh",
      env: {"SERVER_IP" => SERVER_IP}
  end

	# App1
	config.vm.define APP1_NAME do |app_one|
		app_one.vm.hostname = APP1_NAME
		app_one.vm.network "private_network", ip: APP1_IP

    app_one.vm.provision "shell",
      path: "scripts/app_one.sh",
      env: {"SERVER_IP" => SERVER_IP}
  end

  	# App2
	config.vm.define APP2_NAME do |app_two|
		app_two.vm.hostname = APP2_NAME
		app_two.vm.network "private_network", ip: APP2_IP

    app_two.vm.provision "shell",
      path: "scripts/app_two.sh",
      env: {"SERVER_IP" => SERVER_IP}
  end

  	# App3
	config.vm.define APP3_NAME do |app_three|
		app_three.vm.hostname = APP3_NAME
		app_three.vm.network "private_network", ip: APP3_IP

    app_three.vm.provision "shell",
      path: "scripts/app_three.sh",
      env: {"SERVER_IP" => SERVER_IP}
  end

end
