# Part 1

# Setup 2 machinse:
#	One that will be a Server (S)
#	The other that will be a Server Worker (SW)

# Both need to have K3s installed on it

SERVER_NAME = "nguiardS"
SERVER_IP = "192.168.56.110"
WORKER_NAME = "nguiardSW"
WORKER_IP = "192.168.56.111"

Vagrant.configure("2") do |config|
	config.vm.box = "debian/bookworm64"

  config.vm.provider "virtualbox" do |v|
      v.memory = 2048
      v.cpus = 2
  end

	# Server
	config.vm.define SERVER_NAME do |server|
		server.vm.hostname = SERVER_NAME
		server.vm.network "private_network", ip: SERVER_IP

    server.vm.provision "shell",
      path: "scripts/Server.sh",
      env: {"SERVER_IP" => SERVER_IP}
  end

	# ServerWorker
	config.vm.define WORKER_NAME do |serverworker|
		serverworker.vm.hostname = WORKER_NAME
		serverworker.vm.network "private_network", ip: WORKER_IP

    serverworker.vm.provision "shell",
      path: "scripts/ServerWorker.sh",
      env: {"SERVER_IP" => SERVER_IP}

  end
end
