# Part 1

# Setup 2 machinse:
#	One that will be a Server (S)
#	The other that will be a Server Worker (SW)

# Both need to have K3s installed on it

Vagrant.configure("2") do |config|
	config.vm.box = "debian/buster64"

	# Server
	config.vm.define "nguiardS" do |server|
		server.vm.hostname = "nguiardS"
		server.vm.network "private_network", ip: "192.168.56.110"

		# Disable file synchronization with the VM
		server.vm.synced_folder "synced", "/vagrant"

		server.vm.provision "file",
			source: "scripts/Server.sh",
			destination: "/home/vagrant/script.sh"

		server.vm.provision "shell",
			inline: "/bin/sh /home/vagrant/script.sh > /home/vagrant/logs.txt 2>&1"

		server.vm.provider "virtualbox" do |vb|
			vb.memory = "1024" #WARNING -> CHANGE WHEN EVERYTHING IS OK
		end
	end

	# ServerWorker
	config.vm.define "nguiardSW" do |serverworker|
		serverworker.vm.hostname = "nguiardSW"
		serverworker.vm.network "private_network", ip: "192.168.56.111"

		# Disable file synchronization with the VM
		serverworker.vm.synced_folder "synced", "/vagrant"

		serverworker.vm.provision "file",
			source: "scripts/ServerWorker.sh",
			destination: "/home/vagrant/script.sh"

		serverworker.vm.provision "shell",
			inline: "/bin/sh /home/vagrant/script.sh > /home/vagrant/logs.txt 2>&1"

		serverworker.vm.provider "virtualbox" do |vb|
			vb.memory = "1024" #WARNING -> CHANGE WHEN EVERYTHING IS OK
		end
	end
end