# dev vm

Vagrant.configure("2") do |config|
	config.vm.box = "debian/bookworm64"

  config.vm.provider "virtualbox" do |v|
      v.memory = 4096
      v.cpus = 4
  end

	# Server
	config.vm.define "iot" do |server|
		server.vm.hostname = "iot"
    server.vm.network "forwarded_port", guest: 8080, host: 8080

    server.vm.provision "shell", path: "./scripts/installation.sh", name: "installation"
    server.vm.provision "shell", path: "./scripts/setup.sh", name: "setup"
  end
end
